added dob
vamsikrishna2636/test pull request #2
Opened 2020-12-31 12:41 UTC by vamsi-krishna-m

2020-12-31 12:45 UTC, vamsikrishna2636 commented
add some more description

2020-12-31 14:44 UTC, vamsi-krishna-m commented
is all ok

2020-12-31 14:49 UTC, vamsikrishna2636 commented
everything perfect

2020-12-31 14:50 UTC, vamsi-krishna-m reviewed
add points

2020-12-31 14:51 UTC, vamsikrishna2636 reviewed
okkkkkkkkkkk

2020-12-31 14:56 UTC, vamsi-krishna-m reviewed
ok not bad

2020-12-31 14:57 UTC, vamsikrishna2636 requested changes
ghfhgfhgh

2020-12-31 14:58 UTC, vamsikrishna2636 commented
ksjdkgjksd

2021-01-01 10:04 UTC, vamsikrishna2636 reviewed
check the following comments

2021-01-01 10:04 UTC, vamsikrishna2636 commented on README.md
> +date of bith is added to vamsi file.
jai balayya

2021-01-01 10:08 UTC, vamsikrishna2636 commented on vamsi
>  mannam vamsi krishna
hakil

2021-01-01 10:16 UTC, merged